//прога работает.
//плата discoverySTM32L031K6T7STM32L031K6T7

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define IRQNO_TIMER2	28
#define IRQNO_I2C1		31

uint32_t *pNVIC_IPRBase  =(uint32_t*) 0xE000E400;		//Interrupt Priority Register
uint32_t *pNVIC_ISERBase =(uint32_t*) 0xE000E100;		//Interrupt Set-Enable Registers
uint32_t *pNVIC_ISPRBase =(uint32_t*) 0xE000E200;		//Interrupt Set-Pending Registers

void configure_proirity_for_irqs(uint8_t irq_no, uint8_t priority_value)
{
	//1.find out iprx
	uint8_t iprx=irq_no /4;
	uint32_t *ipr= pNVIC_IPRBase+iprx;

	//2.position in iprx
	uint8_t pos=(irq_no %4)*8;

	//3.configure the priority
	*ipr &=~(0xFF <<pos);				//clear priority fields
	*ipr |= (priority_value << pos);	//set priority value
}

int main(void)
{
	//1. Lets configure the priority for the peripherals
	configure_proirity_for_irqs(IRQNO_TIMER2, 0x80);
	configure_proirity_for_irqs(IRQNO_I2C1, 0x70);

	//2. Set the interrupt pending in the NVIC PR
	*pNVIC_ISPRBase |=(1<<IRQNO_TIMER2);
//	*pNVIC_ISPRBAse |=(1<<IRQNO_I2C1);

	//3. Enable the IRQs in NVIC ISER
	*pNVIC_ISERBase |=(1<<IRQNO_I2C1);
	*pNVIC_ISERBase |=(1<<IRQNO_TIMER2);
}

//Обработчики прерываний
	void  TIM2_IRQHandler (void)              			/* TIM2 global interrupt 		*/
	{
		printf("[TIM2_IRQHandler]\n");
		/*Here, we are pending I2C interrupt request manually */
		*pNVIC_ISPRBase |=(1<<IRQNO_I2C1);
		while(1);
	}

	void I2C1_EV_EXTI23_IRQHandler (void)    			/* I2C1 event interrupt and EXTI Line23 interrupt	*/
	{
		printf("[I2C1_EV_IRQHandler]\n");
	}

