/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*D:\Udemy courcies\Master Microcontroller and Embedded Driver Development(MCU1)\1. Notes and Information\MasteringMCU-master\MasteringMCU-master\Resources\Source_code\Workspace\stm32f4xx_drivers
 * PC13 Button, Pressed=LOW
 * PA5 	LED    ONN=High
 * Код рабочий, при нажатии на кнопку светодиод переключается*/
#include<stdint.h>
#include<string.h>
#include "stm32f446xx.h"
#include "stm32f446xx_gpio_driver.h"

#define HIGH 1
#define LOW 0
#define BTN_PRESSED LOW

void delay(void)
{
	// this will introduce ~200ms delay when system clock is 16MHz
	for(uint32_t i = 0 ; i < 50000 ; i ++);
}


void pin_on(GPIO_Handle_t *h) {
	uint32_t mask = 1 << h->GPIO_PinConfig.GPIO_PinNumber;
	h->pGPIOx->ODR = h->pGPIOx->ODR | mask;
}

void pin_off(GPIO_Handle_t *h) {
	uint32_t mask = 1 << h->GPIO_PinConfig.GPIO_PinNumber;
	h->pGPIOx->ODR = h->pGPIOx->ODR & ~mask;
}

int main(void){

	GPIO_Handle_t GpioLedRed, GpioLedGrn,  GPIOBtn;

	memset(&GpioLedRed,0,sizeof(GPIO_Handle_t));
	memset(&GpioLedGrn,0,sizeof(GPIO_Handle_t));
	memset(&GPIOBtn,0,sizeof(GPIO_Handle_t));

	//this is led gpio configuration
	GpioLedRed.pGPIOx = GPIOA;
	GpioLedRed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	GpioLedRed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLedRed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	GpioLedRed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLedRed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	//this is led gpio configuration
	GpioLedGrn.pGPIOx = GPIOA;
	GpioLedGrn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_6;
	GpioLedGrn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLedGrn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	GpioLedGrn.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLedGrn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;


	pin_on(&GpioLedRed);

	pin_on(&GpioLedGrn);

	pin_off(&GpioLedGrn);



	GPIO_PeriClockControl(GPIOA,ENABLE);

	GPIO_Init(&GpioLedRed);
	GPIO_Init(&GpioLedGrn);

	//this is btn gpio configuration
	GPIOBtn.pGPIOx = GPIOC;
	GPIOBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIOBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;
	GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;

	GPIO_PeriClockControl(GPIOC,ENABLE);

	GPIO_Init(&GPIOBtn);

	GPIO_WriteToOutPin(GPIOA,GPIO_PIN_NO_5,GPIO_PIN_RESET);//GPIO_PIN_SET//GPIO_PIN_RESET

	//IRQ configurations
	GPIO_IRQPriorityConfig(IRQ_NO_EXTI15_10,NVIC_IRQ_PRI15);
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI15_10,ENABLE);

    while(1);

}//END MAIN

void EXTI15_10_IRQHandler(void){
   /// delay(); //200ms . wait till button de-bouncing gets over
	GPIO_IRQHandling(GPIO_PIN_NO_13); //clear the pending event from exti line
	GPIO_ToggleOutPin(GPIOA,GPIO_PIN_NO_5);
	delay();
}//EXTI15_10_IRQHandler         			/* EXTI Line[15:10] interrupts
