/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*
  не работает Hello World на плате не подключен пин SWO

 * */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdint.h>
#include<stdio.h>

int main(void)
{
	//1 enable all configurable exceptions....
	uint32_t *pSHCSR=(uint32_t*)0xE000ED24;		//System Handler Control and State Register on page 4-23

	*pSHCSR |=(1<<16);		//mem manage
	*pSHCSR |=(1<<17);		//bus fault
	*pSHCSR |=(1<<18);		//usage fault

	//3 let force the processor to exucute some undefinidet instructions
	uint32_t *pSRAM=(uint32_t*)0x2000C000;
	*pSRAM=0xFFFFFFFF;

	void (*some_address) (void);

	some_address=(void*)0x2000C001;

	some_address();

	//4 analyze the fault



	/* Loop forever */
	for(;;);
}

//2 implement the fault handlers
//**********************************
void	HardFault_Handler (void){
	printf("Exeption: HardFault\n");	fflush(stdout);
	while(1);
}

//**********************************
void	MemManage_Handler (void){
	printf("Exeption: MemManage\n");	fflush(stdout);
	while(1);
}

//**********************************
void	BusFault_Handler (void){
	printf("Exeption: BusFault\n");		fflush(stdout);
	while(1);
}

//**********************************
void	UsageFault_Handler (void){
	uint32_t *pUFSR =(uint32_t*) 0xE000ED2A;
	printf("Exeption: UsageFault\n");			fflush(stdout);
	printf("UFSR= %lx\n",(*pUFSR) & 0xFFFF);	fflush(stdout);
	while(1);
}
