/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*
проект рабочий.
тут буду блинковать ледом на плате NUCLEO-L432KC
если джампер вставлен мигание реже

доки на плату
https://www.st.com/en/evaluation-tools/nucleo-l432kc.html#
доки на микроконтроллер
https://www.st.com/en/microcontrollers-microprocessors/stm32l432kc.html#

*добавид подтяжку.


 LED=ON=1=PB3
 Input pin =PA12
*/

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	pClkCtrlReg->gpioB_en=1;	//LED EN CLK on GPIOB
	pPortBModeReg->moder3=1;	//LED Set pin as OUT

	pClkCtrlReg->gpioA_en=1;	//BUT EN CLK on PA
	pPortAModeReg->moder12=0;	//BUT Set pin as IN

	pPortAPuPdReg->pupdr12=1;	//pull-up connected
//	pPortAPuPdReg->pupdr12=2;	//Pull-down connected

	/* Loop forever */
	while(1){
	uint8_t ButState=pPortAIntReg->idr12;
		if(!ButState){	//Джампер вставлен PA12=0
			//turn on LED
			pPortBOutReg->odr3=1;
			for(uint32_t i=0; i<50000; i++);
			//turn off the LED
			pPortBOutReg->odr3=0;
			for(uint32_t i=0; i<50000; i++);
		}else{
			//turn on LED
				pPortBOutReg->odr3=1;
				for(uint32_t i=0; i<10000; i++);
				//turn off the LED
				pPortBOutReg->odr3=0;
				for(uint32_t i=0; i<10000; i++);
			}//end else
	}//end while


}//END MAIN
