/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdint.h>
#include "main.h" //este un fiesier antet definit de user deaceia il scriem cu ""

void delay(void){
	// this will introduce ~200ms delay when system clock is 16MHz
	for(uint32_t i = 0 ; i < 500000 ; i ++);
}

void ToggleOutPin(GPIOx_ODR_t *pPortAOutReg){
	while(1){
		pPortAOutReg->odr5=1;
		delay();
		pPortAOutReg->odr5=0;
		delay();
	}//end while
}

int main(void){


	GPIO_Handle_t GpioLED;

	GpioLED.pGPIOx=GPIOA;
	GpioLED.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_5;
	GpioLED.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUT;

}


/*	pClkCtrlReg->gpioA_en=1;	//LED EN CLK on GPIOA
	pPortAModeReg->moder5=1;	//LED Set pin as OUT

	pClkCtrlReg->gpioC_en=1;	//BUT EN CLK on PC13
	pPortCModeReg->moder13=0;	//BUT Set pin as IN
void ToggleOutPin(GPIOx_ODR_t *pPortAOutReg);



}


	/* Loop forever */
/*
	while(1){
		pPortAOutReg->odr5=1;
	delay();
		pPortAOutReg->odr5=0;
		delay();
	}//end while

*/

/*
	while(1){
			pPortAOutReg->odr5^=1;
		delay();
			pPortAOutReg->odr5^=1;
			delay();
		}//end while
*/


/*
	while(1){
	uint8_t ButState=!pPortCIntReg->idr13;
		if(!ButState){
			//turn on LED
			pPortAOutReg->odr5=1;
			for(uint32_t i=0; i<100000; i++);
			//turn off the LED
			pPortAOutReg->odr5=0;
			for(uint32_t i=0; i<100000; i++);
		}//end if
	}//end while
*/


//end main
